alert ("до");
try
{
prompt("введите число"); // оператор без ошибки
}
catch(e) // Если есть ошибка, то оператор оператор catch сохраняет эту ошибку в объекте e
{
alert("обработка ошибки: "+e.message);
}
alert("после");